version: '3'

services: 
  dev:
    image: node:10-slim
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run debug"
    ports:
      - 8080:8080
      - 9229:9229
    env_file: .env.dev
