name: Build + Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build function
      run: npm run build
    
    - name: Deploy function
      uses: actions-hub/gcloud@289.0.0
      env:
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        AUTH0_URL: ${{ secrets.AUTH0_URL }}
        AUTH0_ID: ${{ secrets.AUTH0_ID }}
        AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      with:
        args: functions deploy ghProxy --runtime nodejs10 --trigger-http --allow-unauthenticated --set-env-vars=AUTH0_ID=$AUTH0_ID,AUTH0_URL=$AUTH0_URL,AUTH0_SECRET=$AUTH0_SECRET
